---
root:true

extends:
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:react/recommended
  - '@react-native-community'
  - plugin:react-native/all
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 2018
  sorceType: module
  ecmaFeatures:
    jsx; true
plugins:
  - jest
  - '@typescript-eslint'
  - react
  - react-native
setting:
  react:
    version: detect
rules:
  no-console: warn
  yoda: off
  '@typescript-eslint/explicit-function-return-type': off
  react-native/no-raw-text: off
  react-native/sort-styles: off